#  ansible-playbook -i inventory  conditional.yaml 
---
- name: Content Playbook
  hosts: all
  user: ec2-user
  become: yes 
  become_method: sudo 
  gather_facts: yes 
  tasks:    
  - name: Add user bob  to amazon machine
    when: 
    - ansible_facts['distribution'] == "Amazon"
    - ansible_facts['distribution_version'] == "2"
    ansible.builtin.systemd:
      name: httpd
      state: stopped

  - name: Add user bob  to amazon machine
    when: 
    - ansible_facts['distribution'] == "Amazon"
    - ansible_facts['distribution_version'] == "2"
    ansible.builtin.systemd:
      name: crond
      state: stopped

  - name: Add user bob  to amazon machine
    when: 
    - ansible_facts['distribution'] == "Amazon"
    - ansible_facts['distribution_version'] == "2"
    ansible.builtin.systemd:
      name: sbm-agent
      state: stopped


      
  - name: Add user bob  to amazon machine
    when: 
    - ansible_facts['distribution'] == "Amazon"
    - ansible_facts['distribution_version'] == "2"
    ansible.builtin.package:
      name: kernel
      state: latest



  - name: Add user bob  to amazon machine
    when: 
    - ansible_facts['distribution'] == "Amazon"
    - ansible_facts['distribution_version'] == "2"
    ansible.builtin.systemd:
      name: httpd
      state: started

  - name: Add user bob  to amazon machine
    when: 
    - ansible_facts['distribution'] == "Amazon"
    - ansible_facts['distribution_version'] == "2"
    ansible.builtin.systemd:
      name: crond
      state: started

  - name: Add user bob  to amazon machine
    when: 
    - ansible_facts['distribution'] == "Amazon"
    - ansible_facts['distribution_version'] == "2"
    ansible.builtin.systemd:
      name: sbm-agent
      state: started

