#  ansible-playbook -i inventory  get_url.yaml 
---
- name: Content Playbook
  hosts: all
  user: ec2-user
  become: yes 
  become_method: sudo 
  tasks:    



  - name: Download wordpress
    get_url:
      url: https://wordpress.org/wordpress-5.9.tar.gz
      dest: /tmp/wordpress-5.9.tar.gz
      mode: '0440'

  - name: Extract foo.tgz into /var/lib/foo
    ansible.builtin.unarchive:
      src: /tmp/wordpress-5.9.tar.gz
      dest: /tmp/
      remote_src: true