#  ansible-playbook -i inventory  sync.yaml 
---
- name: Sync Folder
  hosts: all
  user: ec2-user
  become: yes 
  become_method: sudo 
  tasks:    
  - name: Copy files/instructions to all remote machines
    synchronize:     # 10 times faster
      src: covid_instructions/
      dest: /tmp/


  # - name: Ensure web content is updated
  #   copy:
  #     src: covid_instructions/
  #     dest: /tmp/