region: "us-east-1"
state: present
vpc_cidr_block: "10.0.0.0/16"
public_subnet1_cidr: "10.0.1.0/24"
public_subnet2_cidr: "10.0.2.0/24"
public_subnet3_cidr: "10.0.3.0/24"
private_subnet1_cidr: "10.0.101.0/24"
private_subnet2_cidr: "10.0.102.0/24"
private_subnet3_cidr: "10.0.103.0/24"
vpc_name: "Module_dev2"
vpc_tenancy: "default"

aws_tags:
  Name: Ansible
  Team: DevOps
  Created_by: Team